name: Pytest Demo
on: [push]
jobs:
  Explore-Pytest-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest --verbose --rootdir=${{ github.workspace }} --collect-only
