name: Pytest Demo
on: [push]
jobs:
  Explore-Pytest-Action:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest ./tests/unit/test_itree_data.py
