name: Pytest Package WINDOWS with recommended installations
on: [push]
jobs:
  Explore-Pytest-Action:
      runs-on: windows-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.7","3.8", "3.9","3.10", "3.11"] #blist compile not working on python 3.10
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Install the package
        run: |
          python setup.py install
          pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install ojson
          pip install ./dist/blist_br_1.3.7b1.tar.gz
          pip install numpy 
        # temporarily install numpy, bug in module's dependencies.
      - name: GitHub Action for pytest
        run: | 
            #python -m pytest ./tests
            pytest ./tests/ --show-capture=all --capture=tee-sys --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results 
        uses: actions/upload-artifact@v3
        with:
           name: pytest-results-${{ matrix.python-version }}.xml
           path: junit/test-results-${{ matrix.python-version }}.xml