name: Pytest Package FreeBSD with recommended installations
on: [push]
jobs:
  Explore-Pytest-Action:
      runs-on: macos-12
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.7","3.8", "3.9"] #blist compile not working on python 3.10
      steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Install the package
        run: |
          python setup.py install
          pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install ojson
          pip install blist
          pip install numpy 
        # temporarily install numpy, bug in module's dependencies.      
      - uses: actions/checkout@v3
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true  
          sync: sshfs
          run: | 
            #python -m pytest ./tests
            pytest ./tests/ --show-capture=all --capture=tee-sys
